pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'pawantoken',
                    url: 'https://github.com/Pawan080397/valid_login.git'
            }
        }

        stage('Setup Virtual Environment') {
            steps {
                bat '''
                "C:\\Users\\tectum23\\AppData\\Local\\Programs\\Python\\Python313\\python.exe" -m venv .venv
                call .venv\\Scripts\\activate
                pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }

        stage('Run Selenium Tests') {
            steps {
                bat '''
                call .venv\\Scripts\\activate
                pytest -v --html=report.html --self-contained-html
                '''
            }
        }
    }

    post {
        always {
            echo 'Publishing HTML Report'
            publishHTML(target: [
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: '.',
                reportFiles: 'report.html',
                reportName: 'Selenium Test Report'
            ])
        }

        success {
            echo '✅ Selenium tests passed'
        }

        failure {
            echo '❌ Selenium tests failed'
        }
    }
}
