pipeline {
    agent any
    stages {
        stage('Install Dependencies') {
            steps { sh 'pip install -r requirements.txt' }
        }
        stage('Run Tests') {
            steps { sh 'pytest --html=reports/html_reports/report.html --self-contained-html' }
        }
        stage('Archive Reports') {
            steps { archiveArtifacts artifacts: 'reports/html_reports/*.html', fingerprint: true }
        }
    }
}